# Generated by Django 5.1.2 on 2024-11-03 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0002_alter_location_lat_alter_location_lng'),
        ('workshop', '0004_location_alter_workshop_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
