# Generated by Django 5.1.2 on 2024-11-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='workshop',
        ),
        migrations.AddField(
            model_name='workshop',
            name='categories',
            field=models.ManyToManyField(to='workshop.category'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='images',
            field=models.ManyToManyField(to='workshop.image'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='links',
            field=models.ManyToManyField(to='workshop.link'),
        ),
        migrations.DeleteModel(
            name='WorkshopImageMapping',
        ),
    ]
