# Generated by Django 5.1.2 on 2024-11-02 23:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_searchfeedback_search_and_more'),
        ('workshop', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersearch',
            name='declined',
        ),
        migrations.RemoveField(
            model_name='usersearch',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='usersearch',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='usersearch',
            name='start_date',
        ),
        migrations.AddField(
            model_name='usersearch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersearch',
            name='ends_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersearch',
            name='starts_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserSearchStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.usersearch')),
                ('workshop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop')),
            ],
        ),
        migrations.DeleteModel(
            name='SearchFeedback',
        ),
    ]
