# Generated by Django 5.1.2 on 2024-11-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_usersearch_lat_usersearch_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearch',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='usersearch',
            name='lng',
            field=models.FloatField(),
        ),
    ]
